### ISSUE TITLE
Impossible to create new table when running docker version

### ISSUE THREAD

**Issue by CryptoNGuns** [itsalb3rt/cloudcsv#45]
**Describe the bug**
When running docker version there is impossible to create table in the "System Setting" menu

**To Reproduce**

Perform operation for installing APP
$ git clone https://github.com/itsalb3rt/cloudcsv.git $ docker-compose up

Perform operation for installing API
$ git clone https://github.com/itsalb3rt/cloudcsv_api.git $ docker-compose up

1. Create new user, 
2. login, 
3. navigate to "System Setting" 
4. Find the "Manage tables" sections
5. Click "Create table" button
6. Choose some columns names, types and name (ex 3.)
7. Try to click save button

**Expected behavior**
Table should be created

Movie from reproducing issue and error that appears:

"DATA NO IN API DOCUMENTATION FORMAT   CERRAR"
https://www.youtube.com/watch?v=beaBTLE94mc

Desktop (please complete the following information):

OS: Tried on both: Centos and Linux Mint
Browser, Firefox, Chrome

**Comment by itsalb3rt** [comment]
Thanks! I check this asap.

**Comment by itsalb3rt** [comment]
Fixed in #46

**Comment by CryptoNGuns** [comment]
Thank you! Best regards :)

**Comment by CryptoNGuns** [comment]
ĥmmm have the changes been commited to docker repo? I still experience it unfortunately.

(Yes I performed docker stop + docker rm on all old instances and performed new installation)

**Comment by itsalb3rt** [comment]
Make a sure you have a new version code of `master` branch;

- Try `git pull origin master`
- Try to remove the project directory and clone again

**Comment by CryptoNGuns** [comment]
I double checked this and still experience this issue :(

**Comment by itsalb3rt** [comment]
Try to get the `API` response like this video and show me the server response.

![cloudcsv](https://user-images.githubusercontent.com/35310226/193038670-b63c0da5-cb6e-4daf-a66f-311eaa8e0ec3.gif)

**Comment by itsalb3rt** [comment]
Any news @CryptoNGuns ? 👀

**Comment by CryptoNGuns** [comment]
"Method not allowed" message appears in the firefox console:
![image](https://user-images.githubusercontent.com/46357919/193601761-c68cdbaf-0733-4cdb-8f56-4d21d9e1b89b.png)

**Comment by itsalb3rt** [comment]
For the information in the tab of the window, you have an old version of the UI, please run `git pull origin master` and build again the frontend.
